package com.example.harmonicminor.navigation

object Routes {
    const val InitialScreen = "InitialScreen"
    const val RegisterScreen = "RegisterScreen"
    const val LoginScreen = "LoginScreen"
    const val SplashScreen = "SplashScreen"
    const val MainScreen = "MainScreen"
    const val TermsScreen = "TermsScreen"
    const val FAQScreen = "FAQScreen"
    const val PasswordResetScreen = "PassWordResetScreen"
    const val FeedbackScreen = "FeedbackScreen"
    const val AddressScreen = "AddressScreen"
    const val EmailUpdateScreen = "EmailUpdateScreen"
    const val HomeScreen = "HomeScreen"
    const val FavouriteScreen = "FavouriteScreen"
    const val SearchScreen = "SearchScreen"
    const val ShoppingCartScreen = "ShoppingCartScreen"
    const val PaymentCorrectScreen = "PaymentCorrectScreen"
    const val MenuScreen= "MenuScreen"
    const val GuitarScreen = "GuitarScreen"
    const val BassScreen = "BassScreen"
    const val DrumsScreen = "DrumsScreen"
    const val PianoScreen = "PianoScreen"
    const val WindScreen = "WindScreen"
    const val DjScreen = "DjScreen"
    const val MicrophonesScreen = "MicrophonesScreen"
    const val SoftwareScreen = "SoftwareScreen"

    const val GuitarDetailScreen = "GuitarDetailScreen"
    const val BassDetailScreen = "BassDetailScreen"
    const val PianoDetailScreen = "PianoDetailScreen"
    const val SoftwareDetailScreen = "SoftwareDetailScreen"
    const val DjDetailScreen = "DjDetailScreen"
    const val DrumsDetailScreen = "DrumsDetailScreen"
    const val MicrophoneDetailScreen = "MicrophoneDetailScreen"
}
